# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='composition',
            unique_together=set([('nutrition', 'food')]),
        ),
    ]
