# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0002_auto_20160424_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='ammount',
            new_name='ammount_per_100g',
        ),
    ]
