# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0004_auto_20160425_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ean_code',
            field=models.CharField(default=None, max_length=13),
        ),
    ]
