# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0007_containertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFood.ContainerType')),
            ],
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='ammount_per_100g',
            new_name='ammount_per_100',
        ),
    ]
