# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0008_auto_20160426_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='ammount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='packages',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myFood.Food'),
            preserve_default=False,
        ),
    ]
