# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0010_food_container_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='ammount_per_100',
            new_name='ammount_per_100_units',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='ammount',
            new_name='ammount_units',
        ),
    ]
