# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0012_auto_20160427_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField(default=1)),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFood.ContainerType')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFood.Food')),
            ],
        ),
    ]
