# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0013_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='calories_per_g',
            field=models.FloatField(default=0),
        ),
    ]
