# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0014_nutrition_calories_per_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='container_type',
        ),
    ]
