# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0016_meal_container_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='container_types',
        ),
    ]
