# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0017_remove_meal_container_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='packages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myFood.Packages'),
            preserve_default=False,
        ),
    ]
