# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 02:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0018_meal_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 1, 2, 1, 46, 895816, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
