# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0019_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='ammount_per_100_units',
            field=models.FloatField(default=0),
        ),
    ]
