# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0021_auto_20160506_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
