# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0022_auto_20160508_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
