# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0024_auto_20160509_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='nutritions_veryfied',
            field=models.BooleanField(default=False),
        ),
    ]
