# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFood', '0025_food_nutritions_veryfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myFood.Manufacturer'),
        ),
    ]
